#!/bin/mksh
# -*- shell -*-

## secure process environment
## (shell settings, default permissions, process limits, signals)
set +auf
umask 022
ulimit -Sc 0
## ignore keyboard interrupts
#trap : SIGINT SIGQUIT
trap : 2 3

## set up default values for variables
PNAME=${0:-rc}
## where additional service subroutine/function definitions are stored
#SUBR=/etc/rc.d/rc.subr
BOOTLOG=/run/bootlog
#PATH=/bin:/sbin:/usr/bin:/usr/sbin
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
PATH=${PATH}:/busybox:/usr/busybox:/toybox:/usr/toybox
export PATH
bb=/sbin/busybox
sh=/bin/mksh
#sh=/bin/dash
test -f "$sh" -a -x "$sh" && export SHELL=$sh
#test -t 0 -o -t 1 -o -t 2 && export TERM=linux
cd /

##
## main
##

## decide what to do based on the script's first argument
case "${1:-}" in
  start | boot )
    start
    exit 0
    ;;
  stop | *down* )
    stop
    exit 0
    ;;
  ?* )
    echo "${0}: unknown option $1"
    echo "usage: $0 start|stop"
    #exit 100
    ;;
esac

## we were just sourced to load function definitions in the case of no args
return 0

